# Data collection settings.
# Intended contents:
# - save root
# - image save rate
# - randomized start / goal behavior
# - number of episodes
data_logger_node:
  ros__parameters:
    use_sim_time: true

    output_dir: "./datasets/run_001"
    save_images: true
    save_metadata_json: true
    save_metadata_csv: false

    image_topic: "/bcr_bot/stereo_camera/left/image_raw"
    camera_info_topic: "/bcr_bot/stereo_camera/left/camera_info"
    odom_topic: "/bcr_bot/odom"

    prompt_topic: "/omnivla/prompt"
    goal_id_topic: "/omnivla/goal_id"
    goal_pose_topic: "/goal_pose"

    sample_rate_hz: 0.5
    sync_slop_sec: 0.20

episode_manager_node:
  ros__parameters:
    use_sim_time: true

    goal_library_path: "./src/omnivla_bringup/config/goal_library.yaml"
    prompt_template_path: "./src/omnivla_bringup/config/prompt_tamplates.yaml"

    prompt_mode: "aliases"
    random_start: true
    random_goal: true
    reset_between_episodes: false

    reset_timeout_sec: 120.0
    episode_length_sec: 120.0
    max_episodes: 60
    min_start_goal_distance: 1.5

    spawn_frame_id: "map"

    publish_prompt_topic: "/omnivla/prompt"
    publish_goal_id_topic: "/omnivla/goal_id"
    publish_goal_pose_topic: "/goal_pose"
